import th1 from "/assets/img/1.png";
import th2 from "/assets/img/2.png";
import th3 from "/assets/img/3.png";
import th4 from "/assets/img/4.png";
import th5 from "/assets/img/5.png";
import th6 from "/assets/img/6.png";
import th7 from "/assets/img/7.png";
import th8 from "/assets/img/8.png";
import th9 from "/assets/img/9.png";
import th10 from "/assets/img/10.png";
import th11 from "/assets/img/11.png";
import th12 from "/assets/img/12.png";
import th13 from "/assets/img/13.png";
import th14 from "/assets/img/14.png";
import th15 from "/assets/img/15.png";
import th16 from "/assets/img/16.png";
import th17 from "/assets/img/17.png";
import th18 from "/assets/img/18.png";
import th19 from "/assets/img/19.png";
import th20 from "/assets/img/20.png";
import th21 from "/assets/img/21.png";
import th22 from "/assets/img/22.png";
import th23 from "/assets/img/23.png";

export const th1Img = th1;
export const th2Img = th2;
export const th3Img = th3;
export const th4Img = th4;
export const th5Img = th5;
export const th6Img = th6;
export const th7Img = th7;
export const th8Img = th8;
export const th9Img = th9;
export const th10Img = th10;
export const th11Img = th11;
export const th12Img = th12;
export const th13Img = th13;
export const th14Img = th14;
export const th15Img = th15;
export const th16Img = th16;
export const th17Img = th17;
export const th18Img = th18;
export const th19Img = th19;
export const th20Img = th20;
export const th21Img = th21;
export const th22Img = th22;
export const th23Img = th23;